name: urban_treasure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  supabase_flutter: ^2.8.4
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^10.1.0


flutter:
  uses-material-design: true
