name: urban_treasure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  flutter_google_places_hoc081098: ^1.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
